title: "Scaling up Falcon: TMVA implementation of neural networks for multi-jet regression"
description: "Falcon is a hadronization simulator based on once a lookup table and now a neural network."
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
