title: "Falcon: A Machine Learning Project Implementing Multi-target Regression for Particle Physics"
description: "Falcon is a hadronization simulator once based on a lookup table and now a neural network."
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
